import type { Card, Noble } from '@/types/game';

export const ALL_CARDS: Card[] = [
  // Tier 1 — 40 cards
  { id: 'c1_01', tier: 1, bonus: 'black', points: 0, cost: { white: 1, blue: 1, green: 1, red: 1 } },
  { id: 'c1_02', tier: 1, bonus: 'black', points: 0, cost: { white: 1, blue: 2, green: 1, red: 1 } },
  { id: 'c1_03', tier: 1, bonus: 'black', points: 0, cost: { blue: 2, green: 2 } },
  { id: 'c1_04', tier: 1, bonus: 'black', points: 0, cost: { blue: 3 } },
  { id: 'c1_05', tier: 1, bonus: 'black', points: 0, cost: { white: 2, red: 2 } },
  { id: 'c1_06', tier: 1, bonus: 'black', points: 0, cost: { green: 1, red: 3, black: 1 } },
  { id: 'c1_07', tier: 1, bonus: 'black', points: 0, cost: { green: 2, red: 1 } },
  { id: 'c1_08', tier: 1, bonus: 'black', points: 1, cost: { red: 4 } },
  { id: 'c1_09', tier: 1, bonus: 'white', points: 0, cost: { blue: 1, green: 1, red: 1, black: 1 } },
  { id: 'c1_10', tier: 1, bonus: 'white', points: 0, cost: { white: 1, green: 1, red: 1, black: 1 } },
  { id: 'c1_11', tier: 1, bonus: 'white', points: 0, cost: { black: 3 } },
  { id: 'c1_12', tier: 1, bonus: 'white', points: 0, cost: { green: 2, red: 1 } },
  { id: 'c1_13', tier: 1, bonus: 'white', points: 0, cost: { white: 2, blue: 2 } },
  { id: 'c1_14', tier: 1, bonus: 'white', points: 0, cost: { green: 3, black: 2 } },
  { id: 'c1_15', tier: 1, bonus: 'white', points: 0, cost: { blue: 1, red: 2, black: 1 } },
  { id: 'c1_16', tier: 1, bonus: 'white', points: 1, cost: { green: 4 } },
  { id: 'c1_17', tier: 1, bonus: 'blue', points: 0, cost: { white: 1, green: 1, red: 1, black: 1 } },
  { id: 'c1_18', tier: 1, bonus: 'blue', points: 0, cost: { white: 1, blue: 1, green: 1, black: 1 } },
  { id: 'c1_19', tier: 1, bonus: 'blue', points: 0, cost: { white: 3 } },
  { id: 'c1_20', tier: 1, bonus: 'blue', points: 0, cost: { blue: 2, green: 2 } },
  { id: 'c1_21', tier: 1, bonus: 'blue', points: 0, cost: { white: 2, red: 1, black: 1 } },
  { id: 'c1_22', tier: 1, bonus: 'blue', points: 0, cost: { white: 1, red: 1, black: 3 } },
  { id: 'c1_23', tier: 1, bonus: 'blue', points: 0, cost: { red: 2, black: 1 } },
  { id: 'c1_24', tier: 1, bonus: 'blue', points: 1, cost: { black: 4 } },
  { id: 'c1_25', tier: 1, bonus: 'green', points: 0, cost: { white: 1, blue: 1, red: 1, black: 1 } },
  { id: 'c1_26', tier: 1, bonus: 'green', points: 0, cost: { white: 1, blue: 1, green: 1, red: 1 } },
  { id: 'c1_27', tier: 1, bonus: 'green', points: 0, cost: { green: 3 } },
  { id: 'c1_28', tier: 1, bonus: 'green', points: 0, cost: { white: 3, black: 2 } },
  { id: 'c1_29', tier: 1, bonus: 'green', points: 0, cost: { blue: 1, green: 2 } },
  { id: 'c1_30', tier: 1, bonus: 'green', points: 0, cost: { white: 2, blue: 1, black: 2 } },
  { id: 'c1_31', tier: 1, bonus: 'green', points: 0, cost: { white: 1, blue: 2, black: 1 } },
  { id: 'c1_32', tier: 1, bonus: 'green', points: 1, cost: { blue: 4 } },
  { id: 'c1_33', tier: 1, bonus: 'red', points: 0, cost: { white: 1, blue: 1, green: 1, black: 1 } },
  { id: 'c1_34', tier: 1, bonus: 'red', points: 0, cost: { blue: 1, green: 1, red: 1, black: 1 } },
  { id: 'c1_35', tier: 1, bonus: 'red', points: 0, cost: { red: 3 } },
  { id: 'c1_36', tier: 1, bonus: 'red', points: 0, cost: { blue: 2, green: 3 } },
  { id: 'c1_37', tier: 1, bonus: 'red', points: 0, cost: { white: 2, green: 1, blue: 1 } },
  { id: 'c1_38', tier: 1, bonus: 'red', points: 0, cost: { white: 1, green: 1, black: 2 } },
  { id: 'c1_39', tier: 1, bonus: 'red', points: 0, cost: { white: 2, black: 1 } },
  { id: 'c1_40', tier: 1, bonus: 'red', points: 1, cost: { white: 4 } },

  // Tier 2 — 30 cards
  { id: 'c2_01', tier: 2, bonus: 'black', points: 1, cost: { white: 3, blue: 2, green: 2 } },
  { id: 'c2_02', tier: 2, bonus: 'black', points: 1, cost: { white: 3, green: 3, black: 2 } },
  { id: 'c2_03', tier: 2, bonus: 'black', points: 2, cost: { blue: 1, green: 4, red: 2 } },
  { id: 'c2_04', tier: 2, bonus: 'black', points: 2, cost: { green: 5, black: 3 } },
  { id: 'c2_05', tier: 2, bonus: 'black', points: 2, cost: { white: 5 } },
  { id: 'c2_06', tier: 2, bonus: 'black', points: 3, cost: { black: 6 } },
  { id: 'c2_07', tier: 2, bonus: 'white', points: 1, cost: { green: 2, red: 2, black: 3 } },
  { id: 'c2_08', tier: 2, bonus: 'white', points: 1, cost: { white: 2, blue: 3, red: 3 } },
  { id: 'c2_09', tier: 2, bonus: 'white', points: 2, cost: { white: 3, black: 2, red: 3 } },
  { id: 'c2_10', tier: 2, bonus: 'white', points: 2, cost: { white: 3, blue: 5 } },
  { id: 'c2_11', tier: 2, bonus: 'white', points: 2, cost: { red: 5 } },
  { id: 'c2_12', tier: 2, bonus: 'white', points: 3, cost: { white: 6 } },
  { id: 'c2_13', tier: 2, bonus: 'blue', points: 1, cost: { white: 2, blue: 2, black: 3 } },
  { id: 'c2_14', tier: 2, bonus: 'blue', points: 1, cost: { blue: 2, green: 3, red: 3 } },
  { id: 'c2_15', tier: 2, bonus: 'blue', points: 2, cost: { blue: 5, black: 3 } },
  { id: 'c2_16', tier: 2, bonus: 'blue', points: 2, cost: { white: 2, red: 1, black: 4 } },
  { id: 'c2_17', tier: 2, bonus: 'blue', points: 2, cost: { black: 5 } },
  { id: 'c2_18', tier: 2, bonus: 'blue', points: 3, cost: { blue: 6 } },
  { id: 'c2_19', tier: 2, bonus: 'green', points: 1, cost: { white: 3, blue: 3, black: 2 } },
  { id: 'c2_20', tier: 2, bonus: 'green', points: 1, cost: { white: 2, red: 3, black: 2 } },
  { id: 'c2_21', tier: 2, bonus: 'green', points: 2, cost: { white: 4, green: 2, red: 1 } },
  { id: 'c2_22', tier: 2, bonus: 'green', points: 2, cost: { red: 5, black: 3 } },
  { id: 'c2_23', tier: 2, bonus: 'green', points: 2, cost: { green: 5 } },
  { id: 'c2_24', tier: 2, bonus: 'green', points: 3, cost: { green: 6 } },
  { id: 'c2_25', tier: 2, bonus: 'red', points: 1, cost: { blue: 3, red: 2, black: 3 } },
  { id: 'c2_26', tier: 2, bonus: 'red', points: 1, cost: { white: 2, green: 1, red: 4 } },
  { id: 'c2_27', tier: 2, bonus: 'red', points: 2, cost: { white: 1, blue: 4, red: 2 } },
  { id: 'c2_28', tier: 2, bonus: 'red', points: 2, cost: { white: 3, blue: 5, green: 2 } },
  { id: 'c2_29', tier: 2, bonus: 'red', points: 2, cost: { blue: 5 } },
  { id: 'c2_30', tier: 2, bonus: 'red', points: 3, cost: { red: 6 } },

  // Tier 3 — 20 cards
  { id: 'c3_01', tier: 3, bonus: 'black', points: 3, cost: { white: 3, blue: 3, green: 5, red: 3 } },
  { id: 'c3_02', tier: 3, bonus: 'black', points: 4, cost: { green: 3, red: 6, black: 3 } },
  { id: 'c3_03', tier: 3, bonus: 'black', points: 4, cost: { white: 7 } },
  { id: 'c3_04', tier: 3, bonus: 'black', points: 5, cost: { white: 7, blue: 3 } },
  { id: 'c3_05', tier: 3, bonus: 'white', points: 3, cost: { white: 3, blue: 5, green: 3, black: 3 } },
  { id: 'c3_06', tier: 3, bonus: 'white', points: 4, cost: { white: 3, blue: 3, red: 6 } },
  { id: 'c3_07', tier: 3, bonus: 'white', points: 4, cost: { black: 7 } },
  { id: 'c3_08', tier: 3, bonus: 'white', points: 5, cost: { black: 7, blue: 3 } },
  { id: 'c3_09', tier: 3, bonus: 'blue', points: 3, cost: { white: 5, blue: 3, green: 3, black: 3 } },
  { id: 'c3_10', tier: 3, bonus: 'blue', points: 4, cost: { white: 6, blue: 3, black: 3 } },
  { id: 'c3_11', tier: 3, bonus: 'blue', points: 4, cost: { red: 7 } },
  { id: 'c3_12', tier: 3, bonus: 'blue', points: 5, cost: { red: 7, green: 3 } },
  { id: 'c3_13', tier: 3, bonus: 'green', points: 3, cost: { white: 3, red: 3, green: 5, black: 3 } },
  { id: 'c3_14', tier: 3, bonus: 'green', points: 4, cost: { white: 3, blue: 6, green: 3 } },
  { id: 'c3_15', tier: 3, bonus: 'green', points: 4, cost: { blue: 7 } },
  { id: 'c3_16', tier: 3, bonus: 'green', points: 5, cost: { blue: 7, black: 3 } },
  { id: 'c3_17', tier: 3, bonus: 'red', points: 3, cost: { blue: 3, green: 3, red: 5, black: 3 } },
  { id: 'c3_18', tier: 3, bonus: 'red', points: 4, cost: { blue: 3, green: 3, red: 3, black: 6 } },
  { id: 'c3_19', tier: 3, bonus: 'red', points: 4, cost: { green: 7 } },
  { id: 'c3_20', tier: 3, bonus: 'red', points: 5, cost: { green: 7, red: 3 } },
];

export const ALL_NOBLES: Noble[] = [
  { id: 'n01', points: 3, requires: { white: 4, red: 4 } },
  { id: 'n02', points: 3, requires: { white: 3, blue: 3, black: 3 } },
  { id: 'n03', points: 3, requires: { white: 4, black: 4 } },
  { id: 'n04', points: 3, requires: { blue: 4, green: 4 } },
  { id: 'n05', points: 3, requires: { blue: 3, red: 3, green: 3 } },
  { id: 'n06', points: 3, requires: { green: 4, red: 4 } },
  { id: 'n07', points: 3, requires: { black: 4, red: 4 } },
  { id: 'n08', points: 3, requires: { white: 3, blue: 3, red: 3 } },
  { id: 'n09', points: 3, requires: { white: 4, blue: 4 } },
  { id: 'n10', points: 3, requires: { black: 3, red: 3, green: 3 } },
];
